#!/bin/bash

rm -rf /Applications/PlexConnect
cd /Applications
git clone git://github.com/iBaa/PlexConnect.git
tar -xvf PlexConnect.tar.gz -C /Applications
cd /Applications/PlexConnect/support/OSX
chmod +x createcert.bash
chmod +x install.bash
./createcert.bash
./install.bash
cd /Applications/PlexConnect/support/aTV_jailbreak
chmod +x install_button.bash
./install_button.bash
cd /Applications
rm PlexConnect.tar.gz
cd /Applications/PlexConnect
cp -rf hosts /
reboot

